### PR TITLE
[fix] multiple select placeholder

### LINKED ISSUE #424: Select placeholder设置无效
image

### PR DESCRIPTION
**Pull request by menggeNiu**
close #424

### CODE REVIEW

**Comment by bipedd** [comment]
https://react-impression-425.surge.sh

File: packages/react-impression/src/components/Select/Select.js [hunk 1]
```diff
@@ -506,7 +509,7 @@ export default class Select extends React.PureComponent {
         {multiple && (
           <div className='select-tags' onClick={this.toggleOptionsHandle}>
             {selectedItem.length <= 0 && (
-              <span className='select-placeholder'>请选择</span>
+              <span className='select-placeholder'>{placeholder}</span>
```
Comment (lusssn) [inline packages/react-impression/src/components/Select/Select.js]: 给个默认值吧
